version: '3.1'
services:
    db:
        image: mysql:8
        volumes:
            - ./db-data:/var/lib/mysql
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: almost
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: admin